- name: Copy file operations
  hosts: all
  tasks:
    - name: Ensure source directory exists
      ansible.builtin.file:
        path: /tmp/source_dir
        state: directory
    
    - name: Create source file
      ansible.builtin.copy:
        dest: /tmp/source_dir/original.txt
        content: "This file will be copied"
    
    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: /tmp/destination_dir
        state: directory
    
    - name: Copy file
      ansible.builtin.copy:
        src: /tmp/source_dir/original.txt
        dest: /tmp/destination_dir/copy.txt
        remote_src: yes
