name: Deploy to Production

on:
  workflow_run:
    workflows: ["3. CI/CD pipeline"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Get version
        id: version
        run: echo "VERSION=$(cat version)" >> $GITHUB_OUTPUT
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Deploy
        run: |
          docker compose -f ./docker-compose.yml down
          docker compose -f ./docker-compose.yml pull
          docker compose -f ./docker-compose.yml up -d

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          release_name: Release v${{ steps.version.outputs.VERSION }}
          body: "Production deployment completed"

      - name: Extract PR metadata
        id: pr-meta
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: json
          script: |
            const runId = context.payload.workflow_run.id;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const { data: run } = await github.rest.actions.getWorkflowRun({
              owner,
              repo,
              run_id: runId
            });

            const commitSha = run.head_sha;

            const { data: prs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner,
              repo,
              commit_sha: commitSha
            });

            if (prs.length === 0) {
              core.setOutput('skip', 'true');
              return;
            }

            const pr = prs[0];
            core.setOutput('pr_number', pr.number);

      - name: Add PROD label
        if: steps.pr-meta.outputs.skip != 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = Number("${{ steps.pr-meta.outputs.pr_number }}");
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels: ['PROD']
            });
